# Generated by Django 5.1.5 on 2025-02-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortDescription', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=100)),
                ('purchaseDate', models.DateField()),
                ('purchaseTime', models.TimeField()),
                ('total', models.CharField(max_length=10)),
                ('items', models.ManyToManyField(to='receipts.item')),
            ],
        ),
    ]
